version: '3'
services:
  app:
    build: .
    container_name: go-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_USER: postgres
      DB_PASSWORD: polkmn1234
      DB_NAME: postgres
      DB_HOST: db
    networks:
      - go-net

  db:
    image: postgres:16
    container_name: postgres-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: polkmn1234
      POSTGRES_DB: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - go-net
    ports:
      - "5431:5432"

networks:
  go-net:
    driver: bridge

volumes:
  postgres-data:
