version: "3"
services:
  database:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: polkmn1234
      POSTGRES_DB: postgres
      DB_HOST: localhost
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - go-net
    ports:
      - "5431:5432"
  e-meeting:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    restart: unless-stopped
    command: go run main.go
    ports:
      - "8080:800"
    depends_on:
      - database
    networks:
      - go-net

networks:
  go-net:
    driver: bridge

volumes:
  postgres-data:
